main:
	python3 main.py < input-0.txt > output-0.txt
	diff -y output-0.txt output-sample-0.txt

	python3 main.py < input-1.txt > output-1.txt
	diff -y output-1.txt output-sample-1.txt

	python3 main.py < input-2.txt > output-2.txt	
	diff -y output-2.txt output-sample-2.txt
